<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<!-- Paquetes NuGet que usa este proyecto -->
	<ItemGroup>
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<!-- A qué otros proyectos de la solución está conectado este -->
	<ItemGroup>
		<ProjectReference Include="..\SubastaYa.Infraestructura\SubastaYa.Infraestructura.csproj" />
		<ProjectReference Include="..\SubastaYa.Servicios\SubastaYa.Servicios.csproj" />
	</ItemGroup>

</Project>